spring.application.name=eureka-server
server.port=8070

eureka.instance.hostname=eurekaserver1
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eurekaserver2:8070/eureka/,http://eurekaserver3:8070/eureka/

spring.cloud.config.uri=http://configserver:8071
spring.cloud.loadbalancer.ribbon.enabled=false