server:
  port: 8072
  
logstash.host: 3.136.161.26:5000
 
logging: 
  config: classpath:logback-delayed.xml
  
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
spring:
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
          - Path=/organization/**
          filters:
          - RewritePath=/organization/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
          - Path=/license/**
          filters:
          - RewritePath=/license/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie

keycloak:
    auth-server-url: http://localhost:8080/auth
    bearer-only: true
    credentials:
        secret: 5988f899-a5bf-4f76-b15f-f1cd0d2c81ba
    realm: spmia-realm
    resource: ostock
    ssl-required: external
    use-resource-role-mappings: true    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
        
